### ISSUE TITLE
Link with Chmy?

### ISSUE THREAD

**Issue by boriskaus** [JuliaGeodynamics/JustPIC.jl#135]
It would be great if `JustPIC` can be made compatible with [Chmy.jl](https://github.com/PTsolvers/Chmy.jl) as well. Or is it too tightly integrated with `ParallelStencil` and `ImplicitGlobalGrid`?

**Comment by albert-de-montserrat** [comment]
JP uses ParallelStencil internally to abstract the backend. I could switch to Chmy (or KernelAbstractions for a lighter dependency) but that would mean a full rewrite with no performance gains; there may even be regressions since Chmy doesnt seem to be very battle tested in CPUs. Perhaps the only place where it could be useful is on the MPI comm but thats a small 

Nonetheless, all the particle objects are independent of ParallelStencil, so they could be used in any code written by Chmy. If there's any incompatibility, should (magic words here) be easy to fix :)

**Comment by boriskaus** [comment]
thanks for the clarification - it would be great to have an example that illustrates how to use the particle objects along with `Chmy`
